ALTER TABLE pricing_items ADD COLUMN features TEXT NOT NULL DEFAULT '[]';
ALTER TABLE pricing_items ADD COLUMN turnaround TEXT NOT NULL DEFAULT '';
ALTER TABLE pricing_items ADD COLUMN revisions TEXT NOT NULL DEFAULT '';
ALTER TABLE pricing_items ADD COLUMN featured INTEGER NOT NULL DEFAULT 0 CHECK(featured IN(0,1));

INSERT INTO pricing_items(id,title,description,price_label,features,turnaround,revisions,featured,enabled,display_order) VALUES
('pricing-elements','UI Elements','Focused assets for an existing interface direction.','Custom quote','["Buttons and states","Icons or counters","Export-ready assets"]','Depends on quantity','Defined per scope',0,1,0),
('pricing-screen','UI Screen','A complete, polished screen designed around the game identity.','Custom quote','["Desktop composition","Responsive layout direction","Organized final assets"]','Defined after brief','Defined per scope',1,1,1),
('pricing-system','Complete UI System','A cohesive visual language across the core player experience.','Custom quote','["Multiple connected screens","Reusable component language","HUD and navigation direction","Delivery organization"]','Project-based','Defined per scope',0,1,2);

UPDATE site_settings SET value='{"biography":"I am Ceniza, a UI designer focused on Roblox experiences. I combine visual hierarchy, usability and game identity to make interfaces that feel natural to use and specific to the world they belong to.","specialties":["Game UI","UI / UX","HUD Design","Inventories","Shop Systems","Responsive UI","Icon Design","Menus"],"tools":["Figma","Roblox Studio","Photoshop"],"styles":[{"name":"Modern","description":"Clear systems with confident hierarchy.","image":"/portfolio/SettingsFrame.png"},{"name":"Stylized","description":"Expressive forms built around the game world.","image":"/portfolio/comision2.png"},{"name":"Horror","description":"Atmospheric interfaces that protect immersion.","image":"/portfolio/comision12.png"},{"name":"Minimal","description":"Purposeful screens without visual noise.","image":"/portfolio/inventario.png"}],"capabilityCards":[{"title":"HUD Systems","description":"Readable status, resources and actions built for moment-to-moment play.","image":"/portfolio/BotonesArriba.png","accent":"lime"},{"title":"Shops that convert","description":"Clear item hierarchy, currency context and confident purchase actions.","image":"/portfolio/ShopFrame.png","accent":"orange"},{"title":"Inventory UX","description":"Scannable collections, categories and selection states that stay usable.","image":"/portfolio/inventario.png","accent":"cream"},{"title":"Menus & Settings","description":"Organized controls with strong grouping and unmistakable interaction states.","image":"/portfolio/SettingsFrame.png","accent":"purple"},{"title":"Custom Icon Language","description":"Buttons and symbols designed as part of the same game identity.","image":"/portfolio/botonescomisiones.png","accent":"blue"},{"title":"Responsive Direction","description":"Layouts considered for desktop, tablet and mobile Roblox players.","image":"/portfolio/comision3.png","accent":"red"}]}' WHERE key='about';
